{% raw %}
name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.6
      - name: Install dependencies
        run: make install
      - name: Run check
        run: make test
      - name: Run complexity-baseline
        run: make complexity-baseline{% endraw %}
